# Generated by Django 4.2.4 on 2023-09-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_ayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('anasayfa_resim', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('adres', models.TextField(blank=True, null=True)),
                ('telefon', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('hakkimizda', models.TextField(blank=True, null=True)),
                ('hakkimizda_baslik', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_baslik', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.TextField(blank=True, null=True)),
                ('baslik', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('ust_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kategoriler', to='dashboard.kategori')),
            ],
        ),
    ]
