# Generated by Django 4.2.3 on 2023-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_baslik_slider_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_ayar',
            name='hakkimizda_resim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
