# Generated by Django 4.2.4 on 2023-09-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_alter_testler_alt_kategori_and_more'),
        ('dashboard', '0007_remove_slider_yazi_site_ayar_sag_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt_kategori',
            name='one_cikan_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_cikan_kategorisi', to='panel.testler'),
        ),
    ]
