# Generated by Django 4.2.4 on 2023-10-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alt_kategori_one_cikan_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_ayar',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
