# Generated by Django 4.2.4 on 2023-10-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_site_ayar_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bize_ulasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('mesaj', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
