# Generated by Django 4.2.4 on 2023-10-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(blank=True, null=True)),
                ('icerik', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategoriler', to='blog.kategoriler')),
            ],
        ),
    ]
