# Generated by Django 4.2.4 on 2023-08-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.TextField(blank=True, null=True)),
                ('category_id', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('question_title', models.TextField(blank=True, null=True)),
                ('question_image', models.TextField(blank=True, null=True)),
                ('wrong_answer_text', models.TextField(blank=True, null=True)),
                ('right_answer_text', models.TextField(blank=True, null=True)),
                ('question_hint', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('user_explanation', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('published', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('not_influence_to_score', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('tag_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
