# Generated by Django 4.2.4 on 2023-08-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('correct', models.TextField(blank=True, null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('placeholder', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='panel.sorular')),
            ],
        ),
    ]
