# Generated by Django 4.2.4 on 2023-09-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_kategoriler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorular',
            name='category_id',
        ),
        migrations.AddField(
            model_name='sorular',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kategoriler', to='panel.kategoriler'),
        ),
    ]
