# Generated by Django 4.2.4 on 2023-09-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_sorular_category_id_sorular_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.TextField(blank=True, null=True)),
                ('post_id', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quiz_image', models.TextField(blank=True, null=True)),
                ('question_ids', models.TextField(blank=True, null=True)),
                ('ordering', models.TextField(blank=True, null=True)),
                ('published', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('intervals', models.TextField(blank=True, null=True)),
                ('quiz_url', models.TextField(blank=True, null=True)),
                ('question_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='panel.kategoriler')),
            ],
        ),
    ]
