# Generated by Django 4.2.4 on 2023-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_testler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriler_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('author_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
