# Generated by Django 4.2.4 on 2023-09-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_kategoriler_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testler',
            name='question_category',
        ),
        migrations.AddField(
            model_name='testler',
            name='quiz_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='panel.kategoriler_test'),
        ),
    ]
