# Generated by Django 4.2.4 on 2023-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_testler_intervals_alter_testler_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('RESIM', 'Resim'), ('MUZIK', 'Müzik'), ('VIDEO', 'Video')], default='RESIM', max_length=6)),
                ('dosya', models.FileField(upload_to='medya_dosyalari/')),
            ],
        ),
    ]
