# Generated by Django 4.2.4 on 2023-09-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_medya'),
    ]

    operations = [
        migrations.AddField(
            model_name='testler',
            name='kullanici_formu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
