# Generated by Django 4.2.4 on 2023-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alanlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='testler',
            name='yanlis_soru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
