# Generated by Django 4.2.4 on 2023-09-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_testler_alanlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonuclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileds', models.JSONField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('ip_adress', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('dogru', models.TextField(blank=True, null=True)),
                ('yanlis', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='panel.testler')),
            ],
        ),
    ]
