# Generated by Django 4.2.4 on 2023-09-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_remove_sonuclar_end_date_remove_sonuclar_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sonuclar',
            old_name='fileds',
            new_name='fields',
        ),
    ]
