# Generated by Django 4.2.3 on 2023-09-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonuclar',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
