# Generated by Django 4.2.4 on 2023-09-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_sonuclar_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
