# Generated by Django 4.2.4 on 2023-09-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_slider_yazi_site_ayar_sag_slider_and_more'),
        ('panel', '0021_rename_first_name_sertifika_isim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testler',
            name='alt_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.alt_kategori'),
        ),
        migrations.AddField(
            model_name='testler',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ust_kategori'),
        ),
    ]
