# Generated by Django 4.2.4 on 2023-09-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_slider_yazi_site_ayar_sag_slider_and_more'),
        ('panel', '0022_testler_alt_kategori_testler_ust_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testler',
            name='alt_kategori',
        ),
        migrations.RemoveField(
            model_name='testler',
            name='ust_kategori',
        ),
        migrations.AddField(
            model_name='testler',
            name='alt_kategori',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.alt_kategori'),
        ),
        migrations.AddField(
            model_name='testler',
            name='ust_kategori',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.ust_kategori'),
        ),
    ]
