# Generated by Django 4.2.4 on 2023-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_slider_yazi_site_ayar_sag_slider_and_more'),
        ('panel', '0023_remove_testler_alt_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testler',
            name='alt_kategori',
            field=models.ManyToManyField(blank=True, to='dashboard.alt_kategori'),
        ),
        migrations.AlterField(
            model_name='testler',
            name='ust_kategori',
            field=models.ManyToManyField(blank=True, to='dashboard.ust_kategori'),
        ),
    ]
