# Generated by Django 4.2.4 on 2023-09-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_alter_testler_alt_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonuclar_alanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sonuclar_alanlari', to='panel.testler')),
            ],
        ),
    ]
