# Generated by Django 4.2.4 on 2023-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_sonuclar_alanlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonuclar',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
