# Generated by Django 4.2.4 on 2023-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_sonuclar_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuclar',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonuclar',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
