# Generated by Django 4.2.4 on 2023-10-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_alter_sonuclar_duration_alter_sonuclar_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cekilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_cekilis', to='panel.testler')),
            ],
        ),
        migrations.CreateModel(
            name='Cekilis_verileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.TextField(blank=True, null=True)),
                ('sinif', models.TextField(blank=True, null=True)),
                ('okul', models.TextField(blank=True, null=True)),
                ('urun', models.TextField(blank=True, null=True)),
                ('resim', models.TextField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('cekilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.cekilis')),
            ],
        ),
    ]
