# Generated by Django 4.2.4 on 2023-10-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_remove_cekilis_alanlar_cekilis_alanlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.TextField(blank=True, null=True)),
                ('durum', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
