# Generated by Django 4.2.4 on 2023-10-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analiz_yayin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yayin_quiz', to='panel.testler')),
            ],
        ),
    ]
