# Generated by Django 4.2.4 on 2023-10-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_analiz_yayin'),
    ]

    operations = [
        migrations.AddField(
            model_name='testler',
            name='yayinlanma_mesaji',
            field=models.TextField(blank=True, null=True),
        ),
    ]
