# Generated by Django 4.2.4 on 2023-10-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_testler_yayinlanma_mesaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='testler',
            name='cekilis_mesaji',
            field=models.TextField(blank=True, null=True),
        ),
    ]
